# Generated by Django 5.2.6 on 2026-03-19 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='nfl.team'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['season_year', 'season_type'], name='nfl_game_season__c6ddc2_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date'], name='nfl_game_date_064f1a_idx'),
        ),
    ]
