# Generated by Django 5.2.6 on 2026-04-03 18:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0002_alter_playergamestats_team_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]
