# Generated by Django 5.2.6 on 2026-04-03 18:49

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0003_auto_20260403_1835'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='game',
            new_name='idx_game_season',
            old_name='nfl_game_season__c6ddc2_idx',
        ),
        migrations.RenameIndex(
            model_name='game',
            new_name='idx_game_date_asc',
            old_name='nfl_game_date_064f1a_idx',
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, default='', help_text='e.g., KC, SF', max_length=5, unique=True),
        ),
        migrations.AddIndex(
            model_name='team',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='idx_player_name_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
