# Generated by Django 5.2.6 on 2026-04-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0004_rename_nfl_game_season__c6ddc2_idx_idx_game_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamoffensereceivingstats',
            name='receptions',
        ),
        migrations.AddField(
            model_name='teamcoverageschemestats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamcoveragestatsbyposition',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamdefensepassingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamdefensereceivingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamdefenserushingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamoffensepassingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamoffenseplaycallingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamoffensereceivingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamoffenserushingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamranksnapshot',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamadvancedefensestats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamadvancedefensestats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_advance_defense', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamadvanceoffensestats',
            name='season_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teamadvanceoffensestats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_advance_offense', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamcoverageschemestats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_coverage_rates', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamcoveragestatsbyposition',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_coverage_stats_by_position', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamdefensepassingstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_defense_passing', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamdefensereceivingstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_defense_receiving', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamdefenserushingstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_defense_rushing', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamoffensepassingstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_offense_passing', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamoffenseplaycallingstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_play_calling', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamoffensereceivingstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_offense_receiving', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamoffenserushingstats',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_offense_rushing', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='teamranksnapshot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_snapshot', to='nfl.team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamadvancedefensestats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamadvanceoffensestats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamcoverageschemestats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamcoveragestatsbyposition',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamdefensepassingstats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamdefensereceivingstats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamdefenserushingstats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamoffensepassingstats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamoffenseplaycallingstats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamoffenserushingstats',
            unique_together={('team', 'season_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teamranksnapshot',
            unique_together={('team', 'season_year')},
        ),
        migrations.AddIndex(
            model_name='teamranksnapshot',
            index=models.Index(fields=['team', 'season_year'], name='idx_rank_team_season'),
        ),
    ]
