# Generated by Django 5.2.6 on 2026-04-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0005_remove_teamoffensereceivingstats_receptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamoffensereceivingstats',
            name='receptions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='teamoffensereceivingstats',
            unique_together={('team', 'season_year')},
        ),
    ]
