# Generated by Django 5.2.6 on 2026-04-06 21:12

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0006_teamoffensereceivingstats_receptions_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='team',
            name='idx_player_name_gin',
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, help_text='e.g., KC, SF', max_length=5, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='player',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='idx_player_name_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
