# Generated by Django 5.2.6 on 2026-04-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0007_remove_team_idx_player_name_gin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamadvancedefensestats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamadvanceoffensestats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamcoverageschemestats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamcoveragestatsbyposition',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamdefensepassingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamdefensereceivingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamdefenserushingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamoffensepassingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamoffenseplaycallingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamoffensereceivingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamoffenserushingstats',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='teamranksnapshot',
            name='season_year',
            field=models.PositiveSmallIntegerField(default=2024),
        ),
    ]
