# Generated by Django 5.2.6 on 2026-05-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0009_alter_teamadvancedefensestats_season_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team', to='nfl.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='e.g., KC, SF', max_length=5, null=True, unique=True),
        ),
    ]
