# Generated by Django 5.2.6 on 2026-05-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0010_alter_player_team_alter_team_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Global Metadata',
            },
        ),
    ]
