# Generated by Django 5.2.6 on 2026-06-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0011_globalmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='draftkings_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='fanduel_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='half_ppr_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='kick_return_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='non_ppr_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='off_fum_rec_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='ppr_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='punt_return_tds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='two_pt_conversions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='yahoo_points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
