# Generated by Django 5.2.6 on 2026-06-03 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0012_playergamestats_draftkings_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamestats',
            name='games_played',
        ),
        migrations.CreateModel(
            name='PlayerSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('season_type', models.IntegerField()),
                ('games_played', models.IntegerField(default=0)),
                ('pass_attempts', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('pass_yards', models.IntegerField(default=0)),
                ('pass_touchdowns', models.IntegerField(default=0)),
                ('interceptions', models.IntegerField(default=0)),
                ('sacks', models.IntegerField(default=0)),
                ('long_passing', models.IntegerField(default=0)),
                ('rush_attempts', models.IntegerField(default=0)),
                ('rush_yards', models.IntegerField(default=0)),
                ('rush_touchdowns', models.IntegerField(default=0)),
                ('long_rushing', models.IntegerField(default=0)),
                ('receptions', models.IntegerField(default=0)),
                ('rec_targets', models.IntegerField(default=0)),
                ('rec_yards', models.IntegerField(default=0)),
                ('rec_touchdowns', models.IntegerField(default=0)),
                ('long_reception', models.IntegerField(default=0)),
                ('fumbles', models.IntegerField(default=0)),
                ('fumbles_lost', models.IntegerField(default=0)),
                ('two_pt_conversions', models.IntegerField(default=0)),
                ('off_fum_rec_tds', models.IntegerField(default=0)),
                ('kick_return_tds', models.IntegerField(default=0)),
                ('punt_return_tds', models.IntegerField(default=0)),
                ('ppr_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('half_ppr_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('non_ppr_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('yahoo_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('draftkings_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('fanduel_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rank_pass_yards', models.IntegerField(blank=True, null=True)),
                ('rank_pass_tds', models.IntegerField(blank=True, null=True)),
                ('rank_rush_yards', models.IntegerField(blank=True, null=True)),
                ('rank_rush_tds', models.IntegerField(blank=True, null=True)),
                ('rank_rec_yards', models.IntegerField(blank=True, null=True)),
                ('rank_rec_tds', models.IntegerField(blank=True, null=True)),
                ('rank_ppr', models.IntegerField(blank=True, null=True)),
                ('rank_half_ppr', models.IntegerField(blank=True, null=True)),
                ('rank_draftkings', models.IntegerField(blank=True, null=True)),
                ('rank_fanduel', models.IntegerField(blank=True, null=True)),
                ('rank_non_ppr', models.IntegerField(blank=True, null=True)),
                ('rank_yahoo', models.IntegerField(blank=True, null=True)),
                ('pos_rank_pass_yards', models.IntegerField(blank=True, null=True)),
                ('pos_rank_pass_tds', models.IntegerField(blank=True, null=True)),
                ('pos_rank_rush_yards', models.IntegerField(blank=True, null=True)),
                ('pos_rank_rush_tds', models.IntegerField(blank=True, null=True)),
                ('pos_rank_rec_yards', models.IntegerField(blank=True, null=True)),
                ('pos_rank_rec_tds', models.IntegerField(blank=True, null=True)),
                ('pos_rank_ppr', models.IntegerField(blank=True, null=True)),
                ('pos_rank_half_ppr', models.IntegerField(blank=True, null=True)),
                ('pos_rank_draftkings', models.IntegerField(blank=True, null=True)),
                ('pos_rank_fanduel', models.IntegerField(blank=True, null=True)),
                ('pos_rank_non_ppr', models.IntegerField(blank=True, null=True)),
                ('pos_rank_yahoo', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='nfl.player')),
            ],
            options={
                'verbose_name_plural': 'Player Season Stats',
                'unique_together': {('player', 'season_year')},
            },
        ),
    ]
