# Generated by Django 5.2.6 on 2026-06-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0013_remove_playergamestats_games_played_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerseasonstats',
            unique_together={('player', 'season_year', 'season_type')},
        ),
    ]
