# Generated by Django 5.2.6 on 2026-06-23 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0014_alter_playerseasonstats_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstats',
            name='historic_team',
            field=models.ForeignKey(blank=True, help_text='The last team the player played for during this specific season.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nfl.team'),
        ),
    ]
