# Generated by Django 6.0.4 on 2026-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0015_playerseasonstats_historic_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier', max_length=255),
        ),
    ]
