# Generated by Django 6.0.4 on 2026-07-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0016_alter_player_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playerseasonstats',
            index=models.Index(fields=['historic_team', 'season_year', 'season_type'], name='nfl_players_histori_3fb2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='teamadvancedefensestats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamadv_team_id_c638b3_idx'),
        ),
        migrations.AddIndex(
            model_name='teamadvanceoffensestats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamadv_team_id_447d76_idx'),
        ),
        migrations.AddIndex(
            model_name='teamcoverageschemestats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamcov_team_id_b1a512_idx'),
        ),
        migrations.AddIndex(
            model_name='teamcoveragestatsbyposition',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamcov_team_id_cee3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='teamdefensepassingstats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamdef_team_id_581e8f_idx'),
        ),
        migrations.AddIndex(
            model_name='teamdefensereceivingstats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamdef_team_id_bd63c6_idx'),
        ),
        migrations.AddIndex(
            model_name='teamdefenserushingstats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamdef_team_id_16a8b6_idx'),
        ),
        migrations.AddIndex(
            model_name='teamoffensepassingstats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamoff_team_id_ae4490_idx'),
        ),
        migrations.AddIndex(
            model_name='teamoffenseplaycallingstats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamoff_team_id_bf60d4_idx'),
        ),
        migrations.AddIndex(
            model_name='teamoffensereceivingstats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamoff_team_id_84015f_idx'),
        ),
        migrations.AddIndex(
            model_name='teamoffenserushingstats',
            index=models.Index(fields=['team', 'season_year'], name='nfl_teamoff_team_id_7f1f8e_idx'),
        ),
    ]
