upstream django_app {
    server backend:8000;
}

server {
    listen [::]:80 default_server deferred;
    listen 80 default_server deferred;
    server_name footballstats.melojello.com melojello.com;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/(nfl|admin|auth) {
        proxy_pass http://django_app;

        proxy_pass_header Cache-Control;
        expires off;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/backend/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /app/backend/mediafiles/;
        expires 30d;
    }
    
    include h5bp/basic.conf;
}